name: Build and Push Docker Image

on:
  issue_comment:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'release')
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Build Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%S:%z")
        VCS_REF=$(git rev-list -1 HEAD)
        VERSION=$(git describe --tags '--match=v*' --dirty)

        docker build \
          --build-arg UID=${{ vars.DOCKER_UID }} \
          --build-arg GID=${{ vars.DOCKER_GID }} \
          --build-arg BUILD_DATE=$BUILD_DATE \
          --build-arg VCS_REF=$VCS_REF \
          --build-arg VERSION=$VERSION \
          -t jisunglim/erigon:latest .

    - name: Push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker push jisunglim/erigon:latest
